image:
  # 服务器保存图片的绝对地址
  abs-tmp-path: /home/admin/storage/
  # 图片前缀
  web-img-path: forum/img/
  # 临时存储目录
  tmp-upload-path: /tmp/forum/
  # 图片访问域名
  cdn-host: https://imgs.hhui.top/
  oss:
    type: local
    endpoint:
    prefix: paicoding/
    ak:
    sk:
    bucket:
    host: